/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package valchanov.georgi;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        System.out.println(Arrays.toString(args));
    }

    public String getGreeting() {
        return "Hello world.";
    }
}
